version: "3.9"
services:
    db:
        container_name: database
        image: mysql:latest
        environment:
            MYSQL_DATABASE: weatherapp
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3306:3306"
